-- >SQL CONSTRAINTS => SQL Constraints are rules applied to table columns to enforce data integrity and accuracy.
USE JUNE;
CREATE TABLE STD_DETAILS(ID INT,NAME VARCHAR(50),CLASS INT);
INSERT INTO STD_DETAILS VALUES(1,"RAHUL",9);
INSERT INTO STD_DETAILS VALUES(2,"ANJU",NULL);
INSERT INTO STD_DETAILS VALUES(1,"MANJU",NULL);
SELECT * FROM STD_DETAILS;
-- >CONSTRAINTS
 -- 1)NOT NULL
 -- 2)UNIQUE
 -- 3)DEFAULT
 -- 4)PRIMARY KEY
 -- 5)FOREIGN KEY
 -- 6)CHECK


-- >(1):NOT NULL => USED FOR ENSURING A COLUMN CANNOT HAVE A NULL VALUE
 -- SYNTAX:CREATE TABLE TBNAME(COLUMN_NAME DTYPE CONSTRAINT_NAME,....);
CREATE TABLE STD1(ID INT NOT NULL, NAME VARCHAR(50));
INSERT INTO STD1 VALUES(1,"ADHIL");
INSERT INTO STD1 VALUES(2,NULL);        -- (HERE NULL RETURNS COZ WE HAVNT MENTIONED NOT NULL IN THE NAME) 
SELECT* FROM STD1;

-- SYNTAX:ALTER TABLE TBNAME MODIFY COLNAME DTPYPE CONSTRAINTS;
ALTER TABLE STD1 MODIFY NAME VARCHAR(50) NOT NULL;

-- >(2):UNIQUE => ENSURES ALL VALUES IN A COLUMN ARE DIFFERENT
CREATE TABLE STD2(ID INT NOT NULL UNIQUE,NAME VARCHAR(50) NOT NULL);
INSERT INTO STD2 VALUES(2,"ADHIL"),(2,"ANU"),(2,"ANJU");     -- (DUPLICATE NAMES ARE NOT ALLOWED)

-- (3):DEFAULT => ASSIGNS A DEFAULT VALUE IF NO VALUE IS PROVIDED 
 -- SYNTAX:CREATE TABLE TBNAME(COLUMN DTYPE DEFAUKT "DEFAULT VALUE",.....);
CREATE TABLE EMPLOYEE(ID INT,NAME VARCHAR(50),CITY VARCHAR(60) DEFAULT "KOCHI");
INSERT INTO EMPLOYEE(ID,NAME) VALUES(100,"ADHIL");
SELECT * FROM EMPLOYEE;         -- (HERE CITY IS NOT MENTIONED BUT IT SETS KOCHI AS DEFAULT)


-- (4):CHECK => ENSURE VALUES SATISFY A SPECIFIC CONDITION
 -- SYNTAX:CREATE TABLE TBNAME(COL_NAME DATATYPE CHECK(CONDITION));
CREATE TABLE STD3(ID INT,NAME VARCHAR(50),AGE INT,CHECK(AGE>=18));
INSERT INTO STD3 VALUES(1,"RAHUL",20);
INSERT INTO STD3 VALUES(2,"ADHIL",17);        -- (RETRUNS ERROR COZ IT DOESNT SATISFY THE CHECK CONDITION)


-- >NORMALIZATION: 
  -- Normalization is the process of organizing data in a database to reduce redundancy (duplicate data) and improve data integrity (accuracy and consistency)

-- (5):PRIMARY KEY => Uniquely identifies each row. It is a combination of NOT NULL and UNIQUE. A table can have only one primary key.
-- SYNTAX:CREATE TABLE TBNAME(COLUMN1 DTYPE NOT NULL UNIQUE,.....,PRIMARY KEY(COLUMN1));
-- EMPLOYEE --> EMP_ID,NAME,DEPT_ID
-- DEPARTMENT --> DEPT_ID,NAME
CREATE TABLE DEPARTMENT(DEPT_ID INT PRIMARY KEY,DEPT_NAME VARCHAR(50));
DESC DEPARTMENT;


-- (6):FOREIGN KEY => A FOREIGN KEY creates a relationship between two tables.
				   -- The foreign key value must already exist in the referenced table.
CREATE TABLE EMPLOYEES(EMP_ID INT PRIMARY KEY,EMP_NAME VARCHAR(50),DEPT_ID INT,FOREIGN KEY(DEPT_ID)REFERENCES DEPARTMENT(DEPT_ID));


 
 
 