CREATE DATABASE CW;
USE CW;
ALTER TABLE txn
RENAME COLUMN `00000000` TO CUSTOMER_ID;

ALTER TABLE txn
RENAME COLUMN `06-26-2011` TO ORDER_DATE;

ALTER TABLE txn
RENAME COLUMN `4007024` TO ORDER_ID;

ALTER TABLE txn
RENAME COLUMN `040.33` TO PRICE;

ALTER TABLE txn
RENAME COLUMN `Exercise & Fitness` TO CATEGORY;

ALTER TABLE txn
RENAME COLUMN `Cardio Machine Accessories` TO PRODUCT;

ALTER TABLE txn
RENAME COLUMN `Clarksville` TO CITY;

ALTER TABLE txn
RENAME COLUMN `Tennessee` TO STATE;

ALTER TABLE txn
RENAME COLUMN `credit` TO PAYMENT_TYPE;

SELECT * FROM txn;

-- 1. Find Row count 
SELECT COUNT(*) AS ROW_COUNT FROM TXN;
-- 2. jan month order_id,cusno,category,product,state 
-- A. Row count 
SELECT ORDER_ID,CUSTOMER_ID,CATEGORY,PRODUCT,STATE FROM TXN WHERE MONTH(STR_TO_DATE(ORDER_DATE,'%m-%d-%Y'))=1;
SELECT COUNT(*) AS JAN_R0W_COUNT FROM TXN WHERE MONTH(STR_TO_DATE(ORDER_DATE,'%m-%d-%Y'))=1;

-- 3. July Month oid,cusno,category,product,state 
-- B. Row count 
SELECT ORDER_ID,CUSTOMER_ID,CATEGORY,PRODUCT,STATE FROM TXN WHERE MONTH(STR_TO_DATE(ORDER_DATE,'%m-%d-%Y'))=7;
SELECT COUNT(*) AS JAN_R0W_COUNT FROM TXN WHERE MONTH(STR_TO_DATE(ORDER_DATE,'%m-%d-%Y'))=7;

-- 4. Each category [count desc sort] 
SELECT CATEGORY, COUNT(*) AS CATEGORY_COUNT FROM TXN GROUP BY CATEGORY ORDER BY CATEGORY_COUNT DESC;

-- 5. Category full deatils 
SELECT CATEGORY FROM TXN;

-- 6. Each paymethod count 
SELECT PAYMENT_TYPE, COUNT(*) AS PAYMENT_COUNT FROM TXN GROUP BY PAYMENT_TYPE;

-- 7. jan-july month purchase count [include] 
SELECT COUNT(*) AS PURCHASE_COUNT FROM TXN WHERE MONTH(STR_TO_DATE(ORDER_DATE,'%m-%d-%Y')) BETWEEN 1 AND 7;

-- 8. Each category total amount 
SELECT CATEGORY, SUM(PRICE) AS TOTAL_AMOUNT FROM TXN GROUP BY CATEGORY;

-- 9. Each category maximum amount 
SELECT CATEGORY, MAX(PRICE) AS MAXIMUM_AMOUNT FROM TXN GROUP BY CATEGORY;

-- 10. Each category avg amount 
SELECT CATEGORY, AVG(PRICE) AS AVERAGE_AMOUNT FROM TXN GROUP BY CATEGORY;

-- 11.total amount by cash and credit card 
SELECT PAYMENT_TYPE, SUM(PRICE) AS TOTAL_AMOUNT FROM TXN GROUP BY PAYMENT_TYPE;

-- 12. Indoor games ,total amount 
SELECT CATEGORY, SUM(PRICE) AS TOTAL_AMOUNT FROM TXN WHERE CATEGORY = 'Indoor Games' GROUP BY CATEGORY;

-- 13. Each state count 
SELECT STATE, COUNT(*) AS STATE_COUNT FROM TXN GROUP BY STATE;
