-- > DATABASE-A database is an organized collection of data that is stored electronically and can be easily accessed, managed, updated, and retrieved.
-- > DBMS-DATABASE MANAGEMENT SYSTEM
-- 2 TYPES
-- >(1):RELATIONAL DATABASE
-- >(2):NON RELATIONAL DATABASE

-- > MySQL < --
-- CRUD=>4 BASIC OPERATIONS PERFORMED ON DATA IN DATABASE 
-- C-CREATE(ADDS NEW RECORD -INSERT)
-- R-READ(SELECT)
-- U-UPDATE(FOR UPDATING AN EXISTING VALUE)
-- D-DELETE(FOR DELETING RECORDS FROM TABLE)

-- SQL COMMANDS => 3 CATEGORIES (3 PAIR ARCHITECTURE)
-- 1)DDL COMMANDS==>DATA DEFINITON LANGUAGE
    -- USED FOR CHANGING STRUCTURES OF THE DATABASE SCHEMAS
    -- CREATE,ALTER,DROP
-- 2)DML COMMANDS==>DATA MANIPULATION LANGUAGE
	-- USED FOR MANAGING DATA WITHIN  THE TABLES
    -- INSERT,UPDATE,DELETE,SELECT
-- 3)DCL COMMANDS==>DATA CONTROL LANGUAGE
	-- USED FOR DEALING WITH THE RIGHTS,PERMISSIONS AND CONTROL OF THE DATABASE SYSTEM
    -- GRANT,REVOKE



 


