USE CLASSICMODELS;
SHOW TABLES;
SELECT * FROM EMPLOYEES;

-- >UPDATE COMMAND => USED TO MODIFY EXISTING DATA IN ONE OR MORE ROWS OF A TABLE
 -- SYNTAX:UPDATE TBNAME SET COL_NAME="NEW VALUE" WHERE CONDITION;
UPDATE EMPLOYEES SET LASTNAME="MURTHY" WHERE EMPLOYEENUMBER=1002;

-- >LIKE OPERATOR => USED TO SEARCH FOR A SPECIFIED PATTERN IN A COLUMN. COMMONLY USED WITH WHERE
SELECT * FROM EMPLOYEES WHERE FIRSTNAME LIKE "A%";
-- "A%"=> STARTS WITH A
-- "%A"=> ENDS WITH A
-- "%AN%"=> CONTAINS AN
SELECT * FROM EMPLOYEES WHERE FIRSTNAME LIKE "%AN%";

-- >BETWEEN CONDITION => USED TO SELECT VALUES WITIHIN A SPECIFIED RANGE
-- ?RETRIEVE EMPLOYEES FROM 1050 TO 1100
SELECT * FROM EMPLOYEES WHERE EMPLOYEENUMBER BETWEEN 1050 AND 1100;

-- >IS NULL => USED TO RETURN THE COLUMNS IF IT'S NULL
SELECT * FROM EMPLOYEES WHERE REPORTSTO IS NULL;
SELECT * FROM EMPLOYEES WHERE LASTNAME IS NULL;

-- >IS NOT NULL => USED TO RETURN THE COLUMNS WITHOUT NULL
SELECT * FROM EMPLOYEES WHERE REPORTSTO IS NOT NULL;


-- >ORDER BY CLAUSE => USED TO SORT THE RECORDS IN THE RESULT SET=>(ASC/DESC)
 -- SYNTAX:SELECT COLUMNS FROM TBNAME ORDER BY COLUMN_NAME ASC/DESC;
-- ?SORTS EMPLOYEENUMBER IN DESCENDING ORDER
SELECT * FROM EMPLOYEES ORDER BY EMPLOYEENUMBER DESC;
-- ?SORTS OFFICECODE IN ASCENDING ORDER
SELECT * FROM EMPLOYEES ORDER BY OFFICECODE ASC;
-- ?SORTS FIRSTNAME IN ASCENDING ORDER
SELECT * FROM EMPLOYEES ORDER BY FIRSTNAME ASC;

-- >DISTINCT CLAUSE => USED TO REMOVE DUPLICATES FROM THE RESULT SET
 -- SYNTAX:SELECT DISTINCT COLUMN_NAMES FROM TBNAME;
SELECT DISTINCT JOBTITLE FROM EMPLOYEES;
SELECT DISTINCT OFFICECODE FROM EMPLOYEES;


-- >MATH FUNCTIONS --
 -- 1)COUNT():TO GET THE COUNT OF ROWS OR NON-NULL VALUES IN A COLUMN
SELECT COUNT(*) AS "PRODUCTS COUNT" FROM PRODUCTS;  
SELECT * FROM PRODUCTS;         
 -- >(ALIAS OPERATOR) = AS IS USED TO ASSIGN A TEMPORARY NAME TO A COLUMN OR TABLE
 
 -- 2)AVG():TO FIND THE AVERAGE VALUE OF A NUMERIC COLUMN 
SELECT AVG(BUYPRICE) AS "AVG PRICE" FROM PRODUCTS;

 -- 3)MIN():TO RETURN THE MINIMUM VALUE IN A COLUMN
SELECT MIN(BUYPRICE) AS "MIN PRICE" FROM PRODUCTS;
 
 -- 4)MAX():USED TO RETURN THE HIGHEST VALUE IN A COLUMN
SELECT MAX(BUYPRICE) AS "HIGHEST PRICE" FROM PRODUCTS; 
 
 -- 5)SUM():USED TO CALCULATE THE TOTAL OF ALL VALUES IN A NUMERIC COLUMN
SELECT SUM(QUANTITYINSTOCK) AS "TOTAL QUANTITY" FROM PRODUCTS; 



-- >GROUP BY CLAUSE => USED TO GROUP ROWS THAT HAVE THE SAME VALUES IN ONE OR MORE COLUMNS.
-- 					=> COMMONLY USED WITH COUNT(),SUM(),AVG(),MAX(),MIN().
SELECT JOBTITLE,COUNT(*) AS "TOTAL EMPLOYEES" FROM EMPLOYEES GROUP BY JOBTITLE;
SELECT PRODUCTLINE,COUNT(*) AS "TOTAL" FROM PRODUCTS GROUP BY PRODUCTLINE;


-- >HAVING CLAUSE => USED TO FILTER THE GROUPS OF ROWS AFTER GROUP BY
SELECT JOBTITLE,COUNT(*) AS "TOTAL EMPLOYEES" FROM EMPLOYEES GROUP BY JOBTITLE HAVING COUNT(*)>5;
-- ? --
SELECT JOBTITLE,COUNT(*) AS "TOTAL EMPLOYEES" FROM EMPLOYEES WHERE OFFICECODE=1 GROUP BY JOBTITLE HAVING COUNT(*)>1;

-- >IMPORTANT ORDER:
  -- SELECT
  -- FROM
  -- WHERE
  -- GROUP BY
  -- HAVING
  -- ORDER BY


-- ?LIMIT COMMAND => USED TO RESTRICT THE NO OF ROWS RETURNED 
 -- SYNTAX:SELECT * FROM STUDENT LIMIT 5;
 