-- >CREATE COMMAND--
 -- CREATING DATABASE
  -- SYNTAX:CREATE DATABASE DBNAME;
CREATE DATABASE JUNE;

 -- LISTING AVAILABLE DATABASES
  -- >SHOW
SHOW DATABASES; 

-- SELECTING REQUIRED DATABASE--
 -- USE
  -- SYNTAX:USE DBNAME;
USE JUNE;

-- LISTING TABLE NAMES--
SHOW TABLES;

-- ? STUDENT TABLE--COLUMNS--STD_ID,NAME,LOC,MARKS 
CREATE TABLE STUDENT(ID INT,NAME VARCHAR(30),LOC VARCHAR(50),MARKS INT);

 -- TABLE STRUCTURE
 DESCRIBE STUDENT;
	-- OR --
 DESC STUDENT;
 
-- >INSERT COMMAND => TO ADD ROWS INTO TABLE
 -- SYNTAX:INSERT INTO TBNAME(VALUE1,VALUE2,....);
INSERT INTO STUDENT VALUES(1,"ADHIL","KOCHI",24),
						(2,"RAJU","CALICUT",20),
                        (3,"AKHIL","PALAKKAD",28);

-- >SELECT COMMAND => TO RETRIEVE(DISPLAY) DATA FROM ONE OR MORE TABLES IN A DATABASE
 -- SYNTAX:SELECT COLUMNS FROM TBNAME;
 SELECT  NAME,MARKS FROM STUDENT;
-- DISPLAY ALL DATA
 -- SYNTAX:SELECT * FROM TBNAME;
SELECT * FROM STUDENT;

-- >DROP COMMAND => TO PERMANENTLY DELETE A DATABASE
 -- SYNTAX:DROP TABLE TBNAME;
DROP TABLE STUDENT;
SHOW TABLES;

-- > ALTER COMMAND =>USED TO MODIFY THE STRUCTURE OF AN EXISTING TABLE(ADDING,DELETING,RENAMING OR CHANGING COLUMNS)

 DESC STUDENT;
 
-- 1)ADDING NEW COLUMN --
 -- SYNTAX:ALTER TABLE TBNAME ADD COLUMN_NAME DATATYPE;
ALTER TABLE STUDENT ADD MAIL VARCHAR(50);

-- 2)MODIFYING A COLUMN'S DEFINITION --
 -- SYNTAX:ALTER TABLE TBNAME MODIFY COLUMN_NAME NEW_DATATYPE;
ALTER TABLE STUDENT MODIFY LOC VARCHAR(70);

-- 3)DELETING A COLUMN --
 -- SYNTAX:ALTER TABLE TBNAME DROP COLUMN COLUMN_NAME;
ALTER TABLE STUDENT DROP COLUMN MAIL;
SELECT * FROM STUDENT;

-- 4)RENAME A COLUMN --
 -- SYNTAX:ALTER TABLE TBNAME RENAME COLUMN OLD_COLUMN_NAME TO NEW_COLUMN_NAME;
ALTER TABLE STUDENT RENAME COLUMN ID TO STD_ID;
ALTER TABLE STUDENTS RENAME COLUMN STD_NAME TO NAME;
ALTER TABLE STUDENTS RENAME COLUMN STD_LOC TO LOC;

-- a)RENAMING A TABLE --
-- SYNTAX=>ALTER TABLE TBNAME RENAME TO NEW_TBNAME;
ALTER TABLE STUDENT RENAME TO STUDENTS;

   -- OPERATORS --
-- 1)RELATIONAL
-- 2)MEMBERSHIP
-- 3)LOGICAL
-- 4)ARITHMETIC

SELECT * FROM STUDENTS;

-- > WHERE CLAUSE=> USED TO FILTER RECORDS BY SPECIFYING CONDITIONS
 -- SYNTAX:SELECT * FROM TBNAME WHERE CONDITIONS;
SELECT * FROM STUDENTS WHERE STD_ID=1;
SELECT STD_ID,NAME FROM STUDENTS WHERE LOC="CALICUT";
-- ?RETRIEVE DATAS OF STD_ID 1 AND 3
SELECT * FROM STUDENTS WHERE STD_ID IN (1,3);

-- >DELETE COMMAND => USED TO DELETE ROWS FROM A TABLE
 -- SYNTAX:DELETE FROM TBNAME WHERE CONDITIONS;
DELETE FROM STUDENTS WHERE STD_ID=3;
SELECT * FROM STUDENTS;
DELETE FROM STUDENTS; 



 





 










 
 
 
 
 
 
 
 
 
 
 