USE CLASSICMODELS;
SHOW TABLES;
SELECT * FROM PAYMENTS;
-- 1.DISPLAY ALL THE PAYMENTS MADE IN 2004
SELECT * FROM PAYMENTS WHERE YEAR(PAYMENTDATE)=2004;

-- 2.FIND ALL PAYMENTS THAT WERE MADE IN THE MONTH OF DECEMBER,REGARDLESS OF THE YEAR
SELECT * FROM PAYMENTS WHERE MONTH(PAYMENTDATE)=12;

-- 3.DISPLAY THE CUSTOMER NUMBER,PAYMENT DATE,AND THE DAY NAME(EG:MONDAY,TUESDAY) FOR EACH PAYMENT
SELECT  CUSTOMERNUMBER,PAYMENTDATE,DAYNAME(PAYMENTDATE) AS DAY_NAME FROM PAYMENTS;

-- 4.FIND ALL PAYMENTS MADE AFTER 2004-06-30
SELECT * FROM PAYMENTS WHERE PAYMENTDATE>"2004-06-30";

-- 5.DISPLAY THE PAYMENT DATE ALONG WITH A NEW COLMN SHOWING THE PAYMENT DATE AFTER ADDING 30 DAYS
SELECT PAYMENTDATE,DATE_ADD(PAYMENTDATE,INTERVAL 30 DAY) AS NEW_DATE FROM PAYMENTS;

-- 6.DISPLAY THE CUSTOMER NUMBER,PAYMENTDATE, AND THE NO OF DAYS PASSED SINCE THE PAYMENT WAS MADE(UPTO TODAYS DATE)
SELECT CUSTOMERNUMBER,PAYMENTDATE,DATEDIFF(CURDATE(),PAYMENTDATE) AS DAYS_SINCE_PAYMENT FROM PAYMENTS;

-- 7.DISPLAY THE CUSTOMERNUMBER,PAYMENT DATE, AND THE MONTH NAME
SELECT CUSTOMERNUMBER,PAYMENTDATE,MONTHNAME(PAYMENTDATE)AS MONTH_NAME FROM PAYMENTS;

-- 8.DISPLAY ALL PAYMENTS MADE ON FRIDAY
SELECT * FROM PAYMENTS WHERE DAYNAME(PAYMENTDATE)="FRIDAY";




-- >NULL FUNCTIONS< --
-- 1)ISNULL() => USED TO CHECK WHETHER A VALUE IS NULL
SELECT ISNULL(7);                        
										-- It returns:
-- 											1 → if the value is NULL 
--                                          0 → if the value is not NULL

-- 2)IFNULL() => REPLACES NULL VALUE WITH ANOTHER VALUES   
 -- SYNTAX:SELECT IFNULL(EXPRESSION,REPLACING_VALUES);
SELECT IFNULL(NULL,7);
 
-- 3)COALESCE() => RETURNS THE FIRST NON NULL VALUE 
 -- SYNTAX:SELECT COALESCE(VALUE1,VALUE2,...);
SELECT COALESCE(NULL,"PYTHON","SQL",7,NULL);

-- 4)NULLIF() => RETURNS NULL IF TWO EXPRESSIONS ARE EQUAL,OTHERWISE RETURNS FIRST EXPRESSION
SELECT NULLIF(10,10);
SELECT NULLIF(10,6);
SELECT 100/NULLIF(2,0);










