-- >STORED PROCEDURE => IT IS A SET OF SQL STATEMENTS STROED IN THE DATABASE UNDER A NAME
 -- Instead of writing the same SQL query again and again, you can save it as a procedure and call it whenever needed.
 -- SYNTAX: CREATING 
-- DELIMITER //
-- CREATE PROCEDURE PROCEDURE_NAME()
-- BEGIN 
-- SQL QUERIES;
-- END //
-- DELIMITER ;

 -- SYNTAX: EXECUTION
-- CALL PROCEDURE_NAME();
USE JOINSS;
DELIMITER //
CREATE PROCEDURE STD_DETAILS()
BEGIN
SELECT * FROM STUDENT;
END //
DELIMITER ;
CALL STD_DETAILS();

SELECT * FROM STUDENT;
-- PROCEDURE WITH INPUT PARAMETERS
DELIMITER //
CREATE PROCEDURE STD_AGE(IN AGE INT)
BEGIN
SELECT * FROM STUDENT WHERE S_AGE=AGE;
END //
DELIMITER ;
CALL STD_AGE(20);

-- PROCEDURE WITH MULTIPLE STATEMENTS
USE WORKS;
SHOW TABLES;
SELECT * FROM EMPLOYEE;
DELIMITER //
CREATE PROCEDURE EMP_SUMMARY()
BEGIN
SELECT COUNT(*) AS TOTAL_EMP_COUNT FROM EMPLOYEE;
SELECT AVG(SALARY) AS AVG_SALARY FROM EMPLOYEE;
END //
DELIMITER ;
CALL EMP_SUMMARY()









  


  
