-- >STRING FUCNTIONS< --
-- 1)LENGTH() => RETURNS THE NO OF CHARACTERS
SELECT LENGTH("PYTHON");

-- 2)UPPER() => CONVERTS TEXT INTO UPPERCASE
SELECT UPPER("python");

-- 3)LOWER() => CONVERTS TEXT INTO LOWERCASE
SELECT LOWER("PYTHON");

-- 4)CONCAT() => JOINS MULTIPLE STRINGS
SELECT CONCAT("DATA"," ","SCIENCE");

-- 5)SUBSTRING() => EXTRACTS PART OF A STRING
 -- SYNTAX:SUBSTRING(STRING,START,LENGTH) 
 SELECT SUBSTRING("DATABASE",5,4);
 
-- 6)LEFT() => RETURNS CHARACTERS FROM THE LEFT
SELECT LEFT("DATABASE",4);

-- 7)RIGHT() => RETURNS CHARACTERS FROM RIGHT
SELECT RIGHT("PYTHON",2);

-- 8)TRIM() => REMOVES SPACES FROM BOTH ENDS
SELECT TRIM("     SQL    ");

-- 9)REPLACE() => REPLACES PART OF A STRING
SELECT REPLACE("I LOVE PYTHON","PYTHON","YOU");

-- 10)REVERSE() => REVERSES A STRING
SELECT REVERSE("PYTHON");


 