-- SUBQUERY => A QUERY INSIDE ANOTHER QUERY. IT IS USED TO RETRIEVE DATA THAT WILL BE USED BY MAIN QUERY
-- SYNTAX:
-- SELECT COL_NAMES 
-- FROM TBNAME 
-- WHERE COL_NAME OPERATOR(
-- 		SELECT COL_NAMES 
--         FROM TBNAME 
--         WHERE CONDITION
--         ); 

USE WORKS;
SELECT * FROM EMPLOYEE;
-- ?:FIND EMPLOYEES WHO EARN MORE THAN AVG RAGE SALARY
SELECT AVG(SALARY) FROM EMPLOYEE;
SELECT * FROM EMPLOYEE
WHERE SALARY>(SELECT AVG(SALARY) 
FROM EMPLOYEE);

-- ?:GET EMPLOYEE DETAILS OF A SPECIFIC DEPARTMENT
USE JOINSS;
SELECT * FROM DEPARTMENT;
SELECT EMP_NAME FROM EMPLOYEE WHERE DEPT_ID IN (SELECT DEPT_ID FROM DEPARTMENT WHERE DEPT_NAME="HR");


-- ?
CREATE TABLE STUDENT (S_ID VARCHAR(10) PRIMARY KEY,S_NAME VARCHAR(50),S_ADDRESS VARCHAR(50),S_PHONE INT,S_AGE INT);
INSERT INTO STUDENT VALUES
('S1', 'RAM', 'CALICUT', '9455123451', 18),
('S2', 'RAMESH', 'GURGAON', '9652431543', 18),
('S3', 'SUJIT', 'ROHTAK', '9156253131', 20),
('S4', 'SURESH', 'DELHI', '9156768971', 18);

CREATE TABLE COURSE(C_ID VARCHAR(10) PRIMARY KEY,C_NAME VARCHAR(50));
INSERT INTO COURSE VALUES('C1', 'DSA'),('C2', 'Programming'),('C3', 'DBMS');

CREATE TABLE STUDENT_COURSE(S_ID VARCHAR(10),
C_ID VARCHAR(10),FOREIGN KEY (S_ID) REFERENCES STUDENT(S_ID),FOREIGN KEY (C_ID) REFERENCES COURSE(C_ID));
INSERT INTO STUDENT_COURSE VALUES('S1', 'C1'),('S1', 'C3'),('S2', 'C1'),('S3', 'C2'),('S4', 'C2'),('S4', 'C3');

SELECT * FROM STUDENT;
SELECT * FROM STUDENT_COURSE;
SELECT * FROM COURSE;
-- (1):Find out names of STUDENTS who have either enrolled in 'DSA' or 'DBMS'?
SELECT S_NAME FROM STUDENT 
WHERE S_ID IN(SELECT S_ID FROM STUDENT_COURSE 
WHERE C_ID IN(SELECT C_ID FROM COURSE 
WHERE C_NAME IN("DSA","DBMS")));

-- (2):Find out S_IDs of STUDENTS who have neither enrolled in 'DSA' nor 'DBMS'?
SELECT S_ID FROM STUDENT 
WHERE S_ID NOT IN(SELECT S_ID FROM STUDENT_COURSE 
WHERE C_ID IN(SELECT C_ID FROM COURSE 
WHERE C_NAME IN("DSA","DBMS")));








