-- USER DEFINED FUNCTIONS(UDF) => A function created by the user/programmer to perform a particular task and return a value.
 -- SYNTAX:
-- DELIMITER $$
-- CREATE FUNCTION FUNC_NAME(PARAMETERS)
-- RETURNS OUTPUT_DATATYPE
-- DETERMINISTIC
-- BEGIN
-- RRETURN OPERATION
-- END $$
-- DELIMITER ;
-- SELECT FUNC_NAME(VALUES);

USE WORKS;
-- ?:SUM OF 2 NUMBERS
DELIMITER $$
CREATE FUNCTION ADD_NUMS(A INT,B INT)
RETURNS INT
DETERMINISTIC
BEGIN
RETURN A+B;
END $$
DELIMITER ;
SELECT ADD_NUMS(10,20) AS "SUMS";

-- ?
DELIMITER $$
CREATE FUNCTION TEN_PERCENT(SALARY DECIMAL(10,2))
RETURNS DECIMAL(10,2)
DETERMINISTIC
BEGIN
RETURN (SALARY*10)/100;
END $$
DELIMITER ;
SELECT TEN_PERCENT(SALARY)AS "TEN PERCENT" FROM EMPLOYEE;









