-- >VIEW => IT'S A VIRTUAL TABLE BASED ON THE RESULT OF SQL QUERY.
--       => View stores the query, not a separate copy of the employee data.
-- >SYNTAX:
-- CREATE VIEW VIEW_NAME AS
-- SELECT * FROM TBNAME;
-- >DISPLAY THE VIEW
-- = SELECT COL_NAMES FROM VIEW_NAME;
USE WORKS;
CREATE VIEW EMP_SAL AS 
SELECT * FROM EMPLOYEE WHERE SALARY>50000;
SELECT * FROM EMP_SAL;
